name: Build Arch package

on:
  push:
    branches:
      - main
    paths:
      - PKGBUILD
      - .github/workflows/build.yml
      - pinned_libs/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare pacman and install build deps
        run: |
          set -euxo pipefail
          sed -i 's/^#Color/Color/' /etc/pacman.conf || true
          sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf || true
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Syu --noconfirm

          # Install base-devel and runtime/build deps required by PKGBUILD
          pacman -S --noconfirm \
            base-devel git curl xz \
            libice gtk3 glu sdl2 sdl2_image sdl2_mixer sdl2_ttf \
            libsndfile libsm openal glew gcc cmake

      - name: Create non-root builder user
        run: |
          set -euxo pipefail
          useradd -m -s /bin/bash builder || true
          chown -R builder:builder "${GITHUB_WORKSPACE}"

      - name: Show workspace (debug)
        run: |
          set -euxo pipefail
          ls -la "${GITHUB_WORKSPACE}"
        shell: bash

      - name: Build package as builder (force bash for makepkg)
        run: |
          set -euxo pipefail
          # Ensure builder exists and workspace ownership is correct
          id builder >/dev/null 2>&1 || useradd -m -s /bin/bash builder
          chown -R builder:builder "${GITHUB_WORKSPACE}"

          # Ensure /bin/sh is bash so makepkg sources PKGBUILD with bash
          if [ -x /bin/bash ]; then
            rm -f /bin/sh || true
            ln -s /bin/bash /bin/sh
          fi

          # Run makepkg as builder in the workspace
          su - builder -c "bash -lc '
            set -euxo pipefail
            cd \"${GITHUB_WORKSPACE}\"
            if [[ -d pinned_libs ]]; then ls -la pinned_libs || true; fi
            export SHELL=/bin/bash
            MAKEFLAGS=\"-j2\" PKGEXT=\".pkg.tar.zst\" makepkg -sf --noconfirm --skippgpcheck
          '"
        shell: bash

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: dwarf-fortress-dfhack-pkg
          path: |
            ${GITHUB_WORKSPACE}/*.pkg.tar.zst
